api = '#'
ADMINS = [1526525522]

TEXT_ASK_ABOUT_FUTURE_PLAN = "Какие планы на день?"
HOUR_ASK_ABOUT_FUTURE_PLAN = 8
MINUTE_ASK_ABOUT_FUTURE_PLAN = 0

TEXT_ASK_OPINION_ABOUT_PLAN = "Как прошел день? Напиши отчет"
HOUR_ASK_OPINION_ABOUT_PLAN = 18
MINUTE_ASK_OPINION_ABOUT_PLAN = 45

WAITING_FOR_THE_USERS_RESPONSE = 40*60

